services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "3443:3443"  
    volumes:
      - ./backend:/app/backend
      - ./database:/app/database
      - ./ssl-dev:/app/ssl 
    env_file:
      - ./backend/.env
    environment:
      - FRONTEND_URL=https://localhost:3000
      - DEBUG=True
      - DATABASE_URL=sqlite:///app/database/library.db
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
      - NODE_OPTIONS=--use-openssl-ca
      - NODE_ENV=development 
    entrypoint: ["/bin/sh", "-c", "mkdir -p /app/database && node src/database/initDb.js && node src/main.js"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: biblioteca-frontend-dev
    ports:
      - "3000:80"
      - "3444:443" 
    volumes:
      - ./ssl-dev:/etc/letsencrypt  
    depends_on:
      - backend
