services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app/backend
      - ./database:/app/database
      - ./ssl:/app/ssl
      - /etc/letsencrypt:/etc/letsencrypt:ro
    env_file:
      - ./backend/.env
    environment:
      - FRONTEND_URL=https://bibliotecamoleculares.com
      - DEBUG=True
      - DATABASE_URL=sqlite:///app/database/library.db
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
      - NODE_OPTIONS=--use-openssl-ca
    entrypoint: ["/bin/sh", "-c", "mkdir -p /app/database && node src/database/initDb.js && node src/main.js"]

  cron:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ["/bin/sh", "-c", "apt-get update && apt-get install -y tzdata && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && sleep 30 && while true; do node scripts/checkOverdues.js; sleep 86400; done"]
    volumes:
      - ./database:/app/database
    environment:
      - DATABASE_URL=sqlite:///app/database/library.db
      - SQLITE_BUSY_TIMEOUT=30000
      - TZ=America/Sao_Paulo
    depends_on:
      - backend

  backup:
    image: ubuntu:latest
    volumes:
      - ./database:/app/database
      - ./scripts:/app/scripts
    environment:
      - GDRIVE_FOLDER_ID=1eCEzS0-vCnmKxin4MUpqDj-QWA28klit
      - TZ=America/Sao_Paulo
    entrypoint: ["/bin/sh", "-c", "apt-get update && apt-get install -y wget curl tzdata rclone jq && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && while true; do /app/scripts/backup_db_to_gdrive.sh; sleep 86400; done"]
    depends_on:
      - backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: biblioteca-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend


  certbot:
    image: certbot/certbot
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: ["/bin/sh", "-c", "trap exit TERM; while true; do certbot renew --webroot -w /var/www/certbot && docker exec biblioteca-frontend nginx -s reload; sleep 86400; done"]
    depends_on:
      - frontend
