services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # HTTP (apenas interno)
      - "3443:3443"  # HTTPS
    volumes:
      - ./database:/app/database
      - ./ssl:/app/ssl
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - DEBUG=False
      - DATABASE_URL=sqlite:///app/database/library.db
    user: "node"
    entrypoint: ["/bin/sh", "-c", "mkdir -p /app/database && node src/database/initDb.js && node src/main.js"]
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"    # HTTP (redirecionamento)
      - "443:443"  # HTTPS
    volumes:
      - ./ssl:/etc/nginx/ssl  # Certificados SSL para Nginx
      - ./nginx-https.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      
  cron:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["sh", "-c", "while true; do node scripts/checkOverdues.js; sleep 86400; done"]
    volumes:
      - ./database:/app/database
    environment:
      - DATABASE_URL=sqlite:///app/database/library.db
    depends_on:
      - backend
