services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001" 
    volumes:
      - ./database:/app/database
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///app/database/library.db
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
      - NODE_OPTIONS=--use-openssl-ca
    user: "node"
    entrypoint: ["/bin/sh", "-c", "mkdir -p /app/database && node src/database/initDb.js && node src/main.js"]
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"  
    depends_on:
      - backend
  cron:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["sh", "-c", "while true; do node scripts/checkOverdues.js; sleep 86400; done"]
    volumes:
      - ./database:/app/database
    environment:
      - DATABASE_URL=sqlite:///app/database/library.db
    depends_on:
      - backend
