services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001" 
    volumes:
      - ./database:/app/database
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///app/database/library.db
    user: "node"
    entrypoint: ["/bin/sh", "-c", "mkdir -p /app/database && npm start"]
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"  
    depends_on:
      - backend
